### ISSUE TITLE
方案缺陷

### ISSUE THREAD

**Issue by cr1992** [idootop/auto_hide_keyboard#1]
1、包裹的区域大小要大于TextField的区域，否则TextField弹窗点击也会收起键盘
2、注册全局监听影响范围较大，如果打开二级页面也会受到影响

**Comment by cr1992** [comment]
问题2感觉需要加入路由判断，加入路由信息记录，如果当前最上层不是注册的路由，则不收起键盘

**Comment by idootop** [comment]
是的，针对这两个问题的处理方法应该比较简单，如果你感兴趣的话，可以根据原理先自行处理一下。如果遇到问题，欢迎继续交流沟通。

**Comment by idootop** [comment]
> 问题2感觉需要加入路由判断，加入路由信息记录，如果当前最上层不是注册的路由，则不收起键盘

靠路由判断并不能解决问题，比如多tab页面的场景。最简单、治本的方法是：查找当前视野内全部可见的输入框组件。
