### ISSUE TITLE
auto_hide_keyboard is incompatible with scan_gun 2.0.2+2

### ISSUE THREAD

**Issue by qcjxberin** [idootop/auto_hide_keyboard#2]
ecause every version of auto_hide_keyboard depends on visibility_detector ^0.4.0+2 and scan_gun 2.0.2+2 depends on visibility_detector ^0.3.3, auto_hide_keyboard is incompatible with scan_gun 2.0.2+2.
And because no versions of scan_gun match >2.0.2+2 <3.0.0, auto_hide_keyboard is incompatible with scan_gun ^2.0.2+2.
So, because pek_bkmket_scan depends on both scan_gun ^2.0.2+2 and auto_hide_keyboard ^1.0.0, version solving failed.

**Comment by idootop** [comment]
Upgrade your flutter to the latest stable version, and make sure your dart version is >= 3.0.0
<img width="475" alt="图片" src="https://github.com/idootop/auto_hide_keyboard/assets/35302658/dea568e3-0028-49d3-b0db-a18c51043101">
